### ISSUE TITLE
ResourceExhaustedError

### ISSUE THREAD

**Issue by dayby** [vanhuyz/CycleGAN-TensorFlow#64]
Hello,when I run your project,raise a error:ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,64,64,256]
	 [[Node: G_6/R256_2/layer2/instance_norm/moments/sufficient_statistics/Sub = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](G_6/R256_2/layer2/Conv2D, G_6/R256_2/layer2/instance_norm/moments/StopGradient)]]
	 [[Node: add_1/_497 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_84861_add_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
can you help me?

**Comment by vanhuyz** [comment]
It seems ran out of memory. What is your environment? Do you train something else at the same time?

**Comment by dayby** [comment]
@vanhuyz Yesterday,I searched the error in Baidu.Someone said it ran out of memory or the batchsize is wrong,but I don't change anything in your code and I don't train something else. My gpu is GeForce GTX1050Ti and the free memory is 3.32GB,so I can't understand why the error happend.

**Comment by thisisiron** [comment]
I resolved this error by reducing the image size.
Ex.
```python3 train.py --image_size 128```

**Comment by codecor-cn** [comment]
> I resolved this error by reducing the image size.
> Ex.
> `python3 train.py --image_size 128`

it works for out of video memory, thanks
